### ISSUE TITLE
Roadmap for version 0.1

### ISSUE THREAD

**Issue by psolymos** [psolymos/EDMAinR#1]
## Data input

- [x] read .xyz landmark data file
- [x] define data object (data is a list of length n, KxD matrices)
- [x] print method for data object (number of landmarks, dims, replicates; names, labels)
- [x] stack method to turn list into stacked X matrix
- [x] subset method: useful for bootstrap; subsetting landmarks, dimensions too

## Nonparametric estimation

- [x] fitting function
- [x] return object structure
- [x] bootstrap method
- [x] print method
- [x] summary method
- [x] plot method: 2D
- [x] plot method: 3D (using FM based MDS and CIs)

## Output from nonparametric estimation

- [x] compare 2 fitted models (numerator vs. denominator)
- [x] form matrix (option to sort the stacked version)
- [x] form difference matrix (FDM) with bootstrap based marginal CIs (option to sort the stacked version)
- [x] bootstrap based T statistic testing
- [x] growth matrix, growth difference matrix (GDM) with bootstrap based marginal CIs
- [x] plot for T statistic distribution
- [x] plot for FDM and GDM
- [ ] save outputs as sheets in xlsx file format

## Parametric estimation

- [x] add different parametric forms forms, most basic: sigma^2*I
- [x] identifiability testing suite: check structural constraints
- [x] user provides a "structure" matrix as input, parametric fit and identifiability testing to follow

## Documentation and testing

- [x] R help files for functions
- [x] imports, namespace, etc (R package checking stuff)
- [x] examples for the help files
- [x] tutorial describing the steps
- [x] add unit tests
- [x] add Linux/Windows CI/CD tests

## Other

- [ ] explore other file formats (see how other packages do it, conversion methods)
- [ ] add parallel option to speed up bootstrap with multiple cores

For features outside of v 0.1, see https://github.com/psolymos/EDMAinR/issues/2

**Comment by psolymos** [comment]
## Questions

- what to do for 2D samples? Have only XY columns, or add Z=0?

**Comment by psolymos** [comment]
3D plot:

- use FM (pairwise distances) with MDS, 
- make a 3D plot with {rgl}
- color edges between landmarks according to >1 or <1 and CI based significance

**Comment by psolymos** [comment]
Parametric estimation of SigmaK:

- [x] SigmaK estimation + identifiability checks
- [ ] use bootstrap results from object to estimate uncertainty for SigmaK
- [ ] add a method to evaluate sensitivity to initial values

**Comment by psolymos** [comment]
Here is a more detailed roadmap for outstanding features and modifications:

## Nonparametric estimation

- [ ] remove mixed bootstrap, allow choosing reference (num, denom) for glogal T test
- [ ] find alternate naming (not T or F)

## Visualization

- [ ] find suitable divergent palette, option to change palette
- [ ] implement 3D plot

## Data checking

- [ ] point cloud around landmarks (as in MorphoJ)
- [ ] mean form + 1 individual at a time (indiv ID prnted), or use average?

## Parametric estimation

- [x] check landmark names when working with pattern matrix
- [x] make non-estimability error optimal (i.e. allow exploration)
- [x] allow parameter names to be numeric (i.e. numbers as characters)

## classification/clustering

- [ ] use SigmaKstar for clustering to see if there are groups
- [ ] predetermined groups, where does it belong? Wishart based likelihood distance ranking

## Influential landmark

- [ ] LOO type assessment, potentially leaving out multiple landmarks and assess global fit / CI?
