### ISSUE TITLE
Roadmap for version 0.2

### ISSUE THREAD

**Issue by psolymos** [psolymos/EDMAinR#2]
- [x] add influential landmarks diagnosis to this package. 
- [ ] 'classification' where a new datum is to be classified to one of the possible groups. One can use EDMA or Procrustes to do that as was mentioned in the purple book. Those two are important methodologies. 
- [ ] prediction of a missing landmark for a datum.

**Comment by psolymos** [comment]
This is now part of v0.1 milestone
